
spring:
  application:
    name: spring-cloud-consumer
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://eureka-node1:8000/eureka/,http://eureka-node2:8001/eureka/,http://eureka-node3:8002/eureka/
