server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka-node1:8000/eureka/,http://eureka-node2:8001/eureka/
  instance:
    hostname: eureka-node3
    prefer-ip-address: false